/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnyLink: typeof import('./src/components/common/AnyLink.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    CombinedSchedule: typeof import('./src/components/schedule/CombinedSchedule.vue')['default']
    CombinedScheduleItem: typeof import('./src/components/schedule/CombinedScheduleItem.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Galleria: typeof import('primevue/galleria')['default']
    GroupItem: typeof import('./src/components/groups/GroupItem.vue')['default']
    GroupLink: typeof import('./src/components/groups/GroupLink.vue')['default']
    GroupSchedule: typeof import('./src/components/schedule/GroupSchedule.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InfoItem: typeof import('./src/components/info/InfoItem.vue')['default']
    InfoList: typeof import('./src/components/info/InfoList.vue')['default']
    InfoTagsList: typeof import('./src/components/info/InfoTagsList.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Panel: typeof import('primevue/panel')['default']
    PhotoSchedule: typeof import('./src/components/schedule/PhotoSchedule.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SpecialtyLink: typeof import('./src/components/specialty/SpecialtyLink.vue')['default']
    SpecialtySelector: typeof import('./src/components/specialty/SpecialtySelector.vue')['default']
    TableSchedule: typeof import('./src/components/schedule/TableSchedule.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TagSelector: typeof import('./src/components/info/TagSelector.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UploadScheduleForm: typeof import('./src/components/admin/UploadScheduleForm.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
