/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CombinedSchedule: typeof import('./src/components/schedule/CombinedSchedule.vue')['default']
    CombinedScheduleItem: typeof import('./src/components/schedule/CombinedScheduleItem.vue')['default']
    DataView: typeof import('primevue/dataview')['default']
    Divider: typeof import('primevue/divider')['default']
    Galleria: typeof import('primevue/galleria')['default']
    GroupLink: typeof import('./src/components/groups/GroupLink.vue')['default']
    GroupSchedule: typeof import('./src/components/schedule/GroupSchedule.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MegaMenu: typeof import('primevue/megamenu')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    PhotoSchedule: typeof import('./src/components/schedule/PhotoSchedule.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TableSchedule: typeof import('./src/components/schedule/TableSchedule.vue')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
