name: "student-schedule"

services:
  backend:
    image: ghcr.io/wandering-cursor/student-schedule:latest
    env_file:
      - .env:/run/secrets/env_file
    ports:
      - "8000:8002"

  database:
    image: postgres:17
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - databaseData:/var/lib/postgresql/data
  
  # pgAdmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: mail@mail.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - ":80"

volumes:
  backendData:
  databaseData:

secrets:
  POSTGRES_DB:
    file: POSTGRES_DB
  POSTGRES_USER:
    file: POSTGRES_USER
  POSTGRES_PASSWORD:
    file: POSTGRES_PASSWORD
  env_file:
    file: .env