# Generated by Django 5.1.3 on 2024-11-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_admin", "0002_photoschedulephoto_photoschedule_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="photo_schedules",
            field=models.ManyToManyField(
                blank=True,
                related_name="schedules",
                to="schedule_admin.photoschedule",
                verbose_name="Photo Schedules",
            ),
        ),
    ]
