# Generated by Django 5.1.3 on 2024-11-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_admin', '0005_photoschedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='photo_schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='photo_schedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_admin.photoschedule', verbose_name='Photo Schedule'),
        ),
    ]
