# Generated by Django 5.1.3 on 2024-11-30 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_admin', '0007_group_groupschedule_schedule_group_schedules_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='for_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 30, 9, 24, 41, 155841, tzinfo=datetime.timezone.utc), verbose_name='For Date'),
            preserve_default=False,
        ),
    ]
