# Generated by Django 5.1.3 on 2024-12-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_admin', '0013_remove_groupschedule_unique_group_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schedule_admin.group'),
        ),
    ]
