# Generated by Django 5.1.4 on 2025-01-02 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_admin", "0016_alter_schedule_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to="info_pages/documents/",
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "color",
                    models.CharField(
                        help_text="HEX color code\nExample: #d48804",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="InfoPage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "related_files",
                    models.ManyToManyField(
                        related_name="info_pages",
                        to="schedule_admin.document",
                        verbose_name="Related files",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="info_pages",
                        to="schedule_admin.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Info page",
                "verbose_name_plural": "Info pages",
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
