# Generated by Django 5.1.5 on 2025-01-25 12:39

import django.db.models.deletion
import schedule_admin.models.teacher.schedule
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule_admin", "0019_alter_infopage_related_files_alter_infopage_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSchedule",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "for_date",
                    models.DateField(
                        default=schedule_admin.models.teacher.schedule.get_tomorrow,
                        verbose_name="For Date",
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teacher_schedule_photos",
                        to="schedule_admin.schedulephoto",
                        verbose_name="Photos",
                    ),
                ),
                (
                    "student_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedule_admin.schedule",
                        verbose_name="Student Schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Schedule",
                "verbose_name_plural": "Teacher Schedules",
                "ordering": ["-for_date"],
                "get_latest_by": "for_date",
            },
        ),
    ]
